name: Prepare

on: [pull_request_target]

jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Labeler
        uses: actions/labeler@v5
        with:
          dot: true
